DATA_TRAIN:
  TYPE: 'CheXpertDataset'
  IMG_DIR: '/home/data_root/chesxpert/'
  LABEL: '/home/data_root/chesxpert/train75.csv'
  CLASS_COL: ['Cardiomegaly', 'Edema', 'Consolidation', 'Atelectasis',  'Pleural Effusion']
  NUM_WORKERS: 2
  IGN_LABEL: -1
DATA_VAL:
  TYPE: 'CheXpertDataset'
  IMG_DIR: '/home/data_root/chesxpert/'
  LABEL: '/home/data_root/chesxpert/valid.csv'
  CLASS_COL: ['Cardiomegaly', 'Edema', 'Consolidation', 'Atelectasis',  'Pleural Effusion']
  NUM_WORKERS: 2
  IGN_LABEL: -1
DATA_TEST:
  USE: 'True'
  TYPE: 'Chest14Dataset'
  IMG_DIR: '/home/data_root/chest14'
  LABEL: '/home/Chest14/Label_Val_Chest14_Full.csv'
  CLASS_COL: ['Cardiomegaly', 'Edema', 'Consolidation', 'Atelectasis',  'Pleural_Thickening']
  IGN_LABEL: -1
  NUM_WORKERS: 0
TRAINING:
  EPOCHS: 20
  BATCH_SIZE: 64
  LR: 0.0001
  LR_USE_DECAY: False
  LR_DECAY_FACTOR: 0.0
  LR_DECAY_STEP: 0
  WEIGHT_DECAY: 0
  ADAM_B1: 0.5
  ADAM_B2: 0.999
EVALUATION:
  BATCH_SIZE: 64
BACKBONE:
  TYPE: 'Res2Net'
  LAYERS: [3, 4, 6, 3]
  BASEWIDTH: 26
  SCALE: 6
  PRETRAIN: 'https://shanghuagao.oss-cn-beijing.aliyuncs.com/res2net/res2net50_26w_6s-19041792.pth'
NECK:
  TYPE: 'FPN_ECA'
  IN_CHANNELS: [512, 1024, 2048]
HEAD:
  TYPE: 'MRFC'
  IN_CHANNELS: [512, 1024, 2048]
  NUM_CLASSES: 5
  LAM: [0.5, 0.3, 0.1]
SELECTION:
  TYPE: 'FPN_VIB'
  IN_CHANNELS: [512, 1024, 2048]
CLASSIFIER:
  TYPE: 'MLRFNet'
LOSS:
  TYPE: 'BiasedFocalLoss'
  BETA: 1.0
  S: 0.2
  ALPHA: 0.4
  REDUCTION: 'mean'
  LOSS_WEIGHT: 1.0
